version: '3'

services:

  mysql-db:
    build: ./.docker/mysql
    container_name: db-app
    restart: always
    tty: true
    ports:
      - "3308:3306"
    volumes:
      - ./.docker/dbdata:/var/lib/mysql
      - ./.docker/mysql:/docker-entrypoint-initdb.d
    environment:
      - MYSQL_ROOT_PASSWORD=admin
      - MYSQL_DATABASE=carlostransportes
      - MYSQL_PASSWORD=admin
      - MYSQL_USER=MainUser